### ISSUE TITLE
Fails on Windows

### ISSUE THREAD

**Issue by techtonik** [Tenchi2xh/Almonds#6]
Gives a lot of these messages:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\Lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "C:\Python27\Lib\multiprocessing\forking.py", line 488, in prepare
    assert main_name not in sys.modules, main_name
AssertionError: __main__
```

Which is a bug which will be fixed in Python 2.7.11 https://hg.python.org/cpython/rev/5d88c1d413b9

**Comment by techtonik** [comment]
Looks like 2.7.11 is already released. http://blog.python.org/2015/12/python-2711-released.html
